### ISSUE TITLE
Test cases generated with `@suite / @test` are not re-evaluated by `mocha --watch`

### ISSUE THREAD

**Issue by jokester** [pana-cc/mocha-typescript#18]
(Just had a look into this repository, but I'm not pretty sure if this problem is of mocha or mocha-typescript. Is there something we can do on this?)

This is a demo of what happens:

- clone [this boilerplate repo](https://github.com/jokester/node-typescript-boilerplate.git) and checkout `demo-mocha-ts-watch` branch.
- run `npm install` and `npm run test:ts:watch`
- change test case in `lib-ts/_test_/test2.ts`: this case gets reevaluated and run again
- change `lib-ts/_test_/test.ts`: does not run again

**Comment by pana-cc** [comment]
I will need some spare time to take a look at this one. At a first glance I don't see `test:ts:watch`, nor `mocha --watch` anywhere in the package.json scripts.

**Comment by jokester** [comment]
Thanks pana-cc, mocha and watch stuff are in [demo-mocha-ts-watch](https://github.com/jokester/typescript-boilerplate/blob/demo-mocha-ts-watch/package.json)

**Comment by pana-cc** [comment]
I've committed some changes that will now implement custom mocha ui. So far the decorators used the global describe/it functions and tests were not registered in the right files. With the commit: https://github.com/pana-cc/mocha-typescript/commit/64c767aa7f20acb947c227fdf37d900f7dc850d9 mocha-typescript can be consumed as custom mocha ui and the decorators for suite and test will report correct files, letting mocha watcher to work a little bit better.

To use the code from master in the boilerplate repo:
 - Clone this repo, do `npm i`, `npm link` in it.
 - Go to the demo-mocha-ta-watch branch in the boilerplate repo and do `npm link mocha-typescript`, `npm i`

To use the mocha-typescript as custom UI, add to the mocha.opts:
```
--ui mocha-typescript
```
And in the `lib-ts/_test_/test.ts`:
```
import "mocha-typescript"; // Get typings
import { expect } from 'chai';

@suite class TestSuite1 {
    @test
    case1() {
        expect(4).to.eq(3);
    }
}
```
You should then be able to use `npm run test:ts:watch`, and make changes both to the test.ts and test2.ts.

mocha-typescript ui will add support for describe/it, suite/test as well the decorators.

I need some more time to better test it, mocha's watcher doesn't seem to work well with "only" for example. Also I managed to break the decorators on one or two occasions where the TypeScript decorators were in incorrect state.

Could you give it a try? I would like to further polish this approach.

On the other hand mocha-typescript ships a watcher, you may consider using it.

**Comment by jokester** [comment]
Thanks pana-cc, the `mocha-typescript` UI worked perfectly for my tests.

**Comment by pana-cc** [comment]
After the refactoring that was supposed to enable typescript-mocha as custom UI, I also figured out the module was capturing the describe/it functions from the first test module and reused them for each and every of the next test modules. So all tests were kind of registered in the first test module. When mocha-typescript is required and @suite @test are now used the describe/it functions are taken from the global on each call which pretty much makes it work in your original setup (the one without custom UI). I will now publish a new version with the changes. There was a lot of stuff moved around I hope I won't break someone. There are plenty of tests for the happy paths but who knows what may brake. The custom UI doesn't have tests yet so I won't consider it as complete feature but I am closing this issue since your boilerplate repo should be good to go. I will be tracking testing and docs on the custom UI as part of #23.
