### ISSUE TITLE
Consider dropping the describe/it functions and use the custom UI API.

### ISSUE THREAD

**Issue by pana-cc** [pana-cc/mocha-typescript#23]
Educate (to myself): https://github.com/mochajs/mocha/wiki/Third-party-UIs

 - [x] Implement mocha-typescript as custom mocha UI.
 - [x] Update the documentation
 - [x] Add unit tests using the custom ui

**Comment by Justus-Maier** [comment]
I could not find any examples for BDD usage of mocha-typescript. Would prefer decorators @describe & @it, instead of @suite/@test but they seem not to exist. Please add example tests for this.

Keep supporting all of mochas test DSLs please!
Becoming an actual & official mocha UI seems like a good idea though :)
