### ISSUE TITLE
'this' context broken in async/after hooks

### ISSUE THREAD

**Issue by ninja-** [pana-cc/mocha-typescript#32]
Hey there,
There seems to be a bug which in some cases breaks 'this' context when executing before/after hooks.
For example, this is part of my code:

```js
    async after() {
        for (let client of this.clients) {
            client.disconnect();
        }
     }
```

When one of the tests fail and after() is executed it fails with "TypeError: Cannot read property 'clients' of undefined"

coming from mocha-typescript code here:

```
				afterEachFunction = noname(function (this: Mocha.IHookCallbackContext) {
					try {
						applyDecorators(this, prototype, prototype.after, instance);
						return prototype.after.call(instance); <<<<
					} finally {
						instance = undefined;
					}
				});

    at Context.<anonymous> (node_modules\mocha-typescript\index.ts:187:30)
```

Do you have any idea on what might be the problem?

**Comment by ninja-** [comment]
also it seems like after() doesnt run when the test timeouts?

**Comment by pana-cc** [comment]
If 'this' is wiped, it is definitely not how it was intended to work. I'll fix it when I have a little spare time.

**Comment by ninja-** [comment]
Thanks a lot <3

**Comment by pana-cc** [comment]
I added several tests and managed to reproduce the issue, but so far I couldn't figure out what is causing the problem. It will take some more time.

**Comment by ninja-** [comment]
Does this happen if you comment out instance = undefined?

**Comment by pana-cc** [comment]
Hi @ninja-,

It turned out I wasn't reproducing it but instead it was something in the tests I made and not the plugin itself. I have added some tests in the plugin about your case that seem to pass: https://github.com/pana-cc/mocha-typescript/blob/dd5cbfacf1d8b4ad84713aaed9be0f4b2c82fe40/tests/repo/custom-ui/test/test.ts#L121

But then after commit the travis build failed, there is some changes in npm and mocha that cause test failures. Perhaps it may be something based on your environment. Could you make a small repo where the problem can be reproduced and add details about you OS, node, npm version etc.

**Comment by pana-cc** [comment]
This is not fixed, I'd need better steps to reproduce.
