### ISSUE TITLE
Running tests through Webstorm 

### ISSUE THREAD

**Issue by Ivaprag** [pana-cc/mocha-typescript#44]
Is it possible to run tests (or suites) through Webstorm IDE _without_ using `npm test`? Pretty much like what is already possible with `mocha`. I want to run just the test or suite I need instead of the entire test base.

**Comment by znk** [comment]
Hello @Ivaprag ,
It seems possible to achieve that with [a hook](1) or [a key binding](2)

[1]: https://www.jetbrains.com/help/webstorm/running-npm-scripts.html#d164270e322
[2]: https://www.jetbrains.com/help/webstorm/binding-macros-with-keyboard-shortcuts.html

Have fun, nub.

**Comment by pana-cc** [comment]
Well, my current workflow (outside webstorm) would be to drop a "only" on the suite ot tests I want to run. So for example if you are working on a specific class you can put a:
``` TypeScript
@suite.only class Test {
  @test one() {}
  @test two() {}
}
@suite class Other {
  @test one() {}
}
```
When you run the typescript compilation and mocha only the tests in the first suite will run.
It is very similar to the vanilla mocha where you would add a `describe.only("suite", () => {`.

Now I don not have WebStore. I had the chance to give it a month free trial and enjoyed it a lot, but at the moment I am using the free opensource VSCode. Is there some additional integration between mocha and WebStorm? Could you share a video for example with features that are available in vanilla mocha and WebStorm that are not available with the mocha-typescript?

**Comment by Ivaprag** [comment]
Hi @pana-cc,

Adding the `only` tag works, it's not perfectly what I'm looking for but it's a good way to do it, thank you!

And about the Webstorm integration, I've use your typescript-mocha-seed project in order to show you what I'm talking about:

![screenshot from 2017-09-13 14-03-20](https://user-images.githubusercontent.com/6988084/30376459-bde8bfd6-988c-11e7-94d2-208046f42af7.png)
_For information, I've had to install the `npm` package `ts-node` in order to run the tests I added under yours._

Those green buttons (surrounded by red rectangles) allow you to run directly your tests (suite) without using `npm test` by just clicking on them (or using shortcut). However, I don't know where or how they have been integrated, sorry.

**Comment by pana-cc** [comment]
Great, I wanted to add something similar in VSCode. I guess there is a "test exploration" utility in WebStorm that figures out which tests on what files and line numbers are. I am not sure how i can plug there so i can provide the necessary meta for the mocha-typescript decorators.

**Comment by segrey** [comment]
WebStorm 2017.3 will support mocha-typescript ([WEB-26940](https://youtrack.jetbrains.com/issue/WEB-26940)). You can try in out in [WebStorm 2017.3 EAP](https://confluence.jetbrains.com/display/WI/WebStorm+EAP).

**Comment by pana-cc** [comment]
Hi @segrey 
I am with mixed feelings.
At first everything looked great with the WEB-26940 for the seed project.
But adding the various mocha-typescript features the behavior quickly degrades.

At first ts-node is far from optimal. It loads each .ts file in a TypeScript project, completely ignoring any tsconfig.json that may be nearby, then tries to compile it and fails in some cases.

Lets go through each of the following tests in the snippets:
```
// Reference mocha-typescript's global definitions:
/// <reference path="../node_modules/mocha-typescript/globals.d.ts" />

import { Unit } from "../src/index";
import { assert } from "chai";

describe("suite", () => {
    it("has test", () => {
        // Trying to run the "suite has test" will fail in WebStorm for "suite is not defined"
        // The reason is that WebStorm will figure out it should use bdd
        // instead of the mocha-typescript ui, and while it does so the "suite" and "test"
        // will be undefined for the test class below.
        // N.B. WebStorm Mocha configuration can be configured to use mocha-typescript reporter and this will suppress the automatically detected reporter.
    });
});

// These work like a charm, I am very happy with them
@suite class UnitTest extends Unit {
    @test "big is true with big number"() {
        assert(this.big(200));
    }
    @test "big is false with small number"() {
        assert(!this.big(300));
    }
}

@suite("One")
class TheTestClass {
    @test("second")
    hasSomeTesting() {
        // The test exploration figures out this is a "TheTestClass hasSomeTesting"
        // while it is "One second", to let proper naming the decorators may accept a string as first argument and use it as a name. Please note it may also be an object like `@suite(timeout(2000)) class`... but if you are doing static analysis figuring out just a string literal as first arg to use as a name should suffice.
        // N.B. I don't think I can currently do something about this problem. Is the test exploration in WebStorm open sourced? 
    }
}

// Nested suites doesn't work at all, notes same as above.
describe("Nested suites", () => {
    @suite class A {
        @test a() {
            // This is not detected as a test
        }
    }
    @suite class B {
        @test b() {}
    }
});
```

I want to implement the tests exploration. I will probably need to do something similar if I am to integrate it with VSCode anyway. Also I want to implement the test runner as I see fit. I would prefer to add some kind of hook that is provided the test name or suite to run, and do the typescript compilation based on the test tsconfig.json as well as run the mocha with all the settings in the test/mocha.opts.

I kind of managed to add a:
 - "Before launch" > "Run external tool" > "Program: npm, Parameters: run pretest", that is added as npm script in the package.json to run the typescript compilation
 - "--opts test/mocha.opts" in the "Extra Mocha Options"
 - set the reporter to "mocha-typescript" to suppress WebStorm passing the detected ui instead of using the one specified in the mocha options. (This is somewhat redundant, the reporter is already specified in the mocha.opts)

But from that point on, when I click run on a test, WebStorm's mocha integration:
 - passes `--grep <testname>`
 - provides the path to the test file to mocha as argument

I really need to suppress the last one, the test may be in a .ts file but when mocha is running it should be loaded from the transpired .js file in the pretest step. ts-node doesn't respect the tsconfig.json files, if the compilation depends on type information the output will differ than the one produced by `tsc -p <tsconfig>`. There are source maps and everything needed for debugging. When such a test is generated, WebStorm adds a config for running a single test and it points to a .ts file, if I manually change it to point to the .js file it works like a charm. For now the mocha-typescript will have to stick with ts-node for WebStorm.

Perhaps I will need some more time to figure all the config things out. But I will definitely add a section about using WebStorm with mocha-typescript in the readme!

**Comment by pana-cc** [comment]
Also the result of each test is displayed twice in the Test Results pane.

**Comment by pana-cc** [comment]
I've added "UnitTests" run configuration to the seed here: https://github.com/pana-cc/mocha-typescript-seed/commit/3a7fedaa6d43fd0df873aad337c850bddb3d093d
Running the "UnitTests" have a before launch task to run TypeScript compilation with the tsconfig in the repo. The configuration in the WebStorm has a little bit redundant data that is duplicated in mocha.opts but that's not a big deal.

With this one I added "ts-node" so that running individual tests using WebStorm may somehow work: https://github.com/pana-cc/mocha-typescript-seed/commit/962f4abf649f1462ce805a63c1da3cd52f46048d
It should be fine as long as one does not mix bdd and mocha-typescript interfaces, mixing tdd and mocha-typescript seems to work. Setting the defaults for WebStorm's "Mocha" task to use "mocha-typescript" works in both cases. The test however still run twice and I can't figure out why :(

**Comment by pana-cc** [comment]
I figured it out. Even if I don't pass the `--opts test/mocha.opts`, mocha loads it by default. The `test/test.js` is referenced there. And since WebStorm uses `ts-node` to load the `test/test.ts` as a module it can't figure out that the `test/test.js` that comes from mocha.opts is the same module and finds the name of the test to run in both files (the .ts and the .js) running the test twice.

**Comment by segrey** [comment]
@pana-cc Thank you very much for the feedback! Indeed, currently ts-node is required, and it'd be nice to run transpiled .js file. However, it's not clear how to locate a transpiled .js file for a given .ts file. Maybe some heuristic would work. If you have thoughts on this topic, please share. The same issue (IDE runs .ts instead of transpiled .js file) arises in other test runners, so it's not specific to mocha or mocha-typescript. Most likely, it should be fixed in a common place, not in mocha test runner integration.
I've files some issues according to your examples:
https://youtrack.jetbrains.com/issue/WEB-28814
https://youtrack.jetbrains.com/issue/WEB-28817

Regarding this example:
```
// Nested suites doesn't work at all, notes same as above.
describe("Nested suites", () => {
    @suite class A {
        @test a() {
            // This is not detected as a test
        }
    }
    @suite class B {
        @test b() {}
    }
});```
Is it common to have such mixed tests? If no, I'd prefer to put it in a backlog for now.

>Is the test exploration in WebStorm open sourced?
No, unfortunately.

>The configuration in the WebStorm has a little bit redundant data that is duplicated in mocha.opts but that's not a big deal.
Indeed, there is a duplication. Don't see a good way to deal with it.

**Comment by pana-cc** [comment]
@segrey Great work!
I have updated the readme of mocha-typescript and referenced WebStorm in the readme. You can check the last commits in the repo or https://www.npmjs.com/package/mocha-typescript#webstorm

I hope I used the logo complying with your style guides.

Overall I am pretty happy with the integration!

This issue: https://youtrack.jetbrains.com/issue/WEB-28814 is something that is easily resolved if you set "mocha-typescript" as test ui in the Default > Mocha task in the tasks configuration dialog. I added this to the README.md I think. You can close this issue as resolved.

This is somewhat high prio IMO: https://youtrack.jetbrains.com/issue/WEB-28817

"Nestled class suites" is how what I'd call putting a `@suite` inside a `suite("..."`, this is not common but is very convenient when one have to organize tests, but can definitely be postponed.

About the duplicated configuration, I don't mind it. The test/mocha.opts could store the options and share them for the npm scripts and the WebStorm, similar to the way TypeScript configuration is put in tsconfig.json, but again, its ok.

And finally about the duplicate test run:
```
However, it's not clear how to locate a transpiled .js file for a given .ts file. Maybe some heuristic would work. 
```
Currently the heuristic to provide the ts to the mocha work relatively well, until it is messed with my test/mocha.opts. I don't think you should do much about it. One solution that comes to my mind would be to configure the Default > Mocha, when spawning a task to run a single test, to omit the setting of a "single file" but preserve something like the set of "run all files in folder recursively", since the "--grep <test name>" in that case will do the proper filter and still run only the test in focus. Does this sound reasonable?

**Comment by segrey** [comment]
@pana-cc Thank you for referencing WebStorm in the readme! It looks good to me. // cc @prigara

>This issue: https://youtrack.jetbrains.com/issue/WEB-28814 is something that is easily resolved if you set "mocha-typescript" as test ui in the Default > Mocha task in the tasks configuration dialog. I added this to the README.md I think. You can close this issue as resolved.

Thanks for the workaround. Let's keep the issue open as it'd be better to detect mocha-typescript UI out-of-the-box.

>This is somewhat high prio IMO: https://youtrack.jetbrains.com/issue/WEB-28817

Will be fixed in the next WebStorm 2017.3 EAP.


>"Nestled class suites" is how what I'd call putting a @suite inside a suite("...", this is not common but is very convenient when one have to organize tests, but can definitely be postponed

Filed as https://youtrack.jetbrains.com/issue/WEB-28854

>One solution that comes to my mind would be to configure the Default > Mocha, when spawning a task to run a single test, to omit the setting of a "single file" but preserve something like the set of "run all files in folder recursively", since the "--grep " in that case will do the proper filter and still run only the test in focus.

Sorry, not sure "Default > Mocha" can be used like this as the selected radio button ("All in directory", ...,  "Test") is determined by the context place (right-click in Project View or in the editor). Yes, running all test files with --grep would work (BTW, good idea!). However, it would make running a single test/suite/file slower as all test files would need to be `require`'ed first.

**Comment by prigara** [comment]
Hi @pana-cc! Thanks for adding a how-to for WebStorm to the readme file! Appreciate that!

**Comment by PanayotCankov** [comment]
Ok, I am closing this issue. I am quite happy with its current state actually.

@segrey, as for the tests and the --grep thing, I would really prefer to rely on the mocha.opts to list all test files and just --grep. In one of the bigger test suites in {N} we have tests that add before and after handlers on the global suite, they create an appium server and attach appium driver, listing just a single test file when trying to execute a single test will fail in that case as the hooks will miss. This may be workaround perhaps by adding --require somewhere but still, IMHO it would be better to just run `mocha --grep <test>`, rather than trying to figure out all the settings on your own. But anyway, it currently works well enough.
